name: 'Verify'

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches:
      - '*'

jobs:
  build-and-verify:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20']
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v3
        if: matrix.java != 8
        with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}
      - name: 'Prepare JDK${{ matrix.java }} env var'
        shell: bash
        run: echo "JDK${{ matrix.java }}=$JAVA_HOME" >> $GITHUB_ENV
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: 8
      - name: Prepare JDK8 env var
        shell: bash
        run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
      - name: 'Build Polyfill'
        uses: gradle/gradle-build-action@v2
        with:
            arguments: "testOn${{ matrix.java }}"
