name: 'Verify'

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches:
      - '*'

jobs:
  build-and-verify:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '9', '10', '11', '12', '13', '14', '15', '16', '17']
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v2
        if: matrix.java != 8
        with:
            distribution: 'adopt'
            java-version: ${{ matrix.java }}
      - name: 'Prepare JDK${{ matrix.java }} env var'
        shell: bash
        run: echo "JDK${{ matrix.java }}=$JAVA_HOME" >> $GITHUB_ENV
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v2
        with:
            cache: 'gradle'
            distribution: 'adopt'
            java-version: 8
      - name: Prepare JDK8 env var
        shell: bash
        run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
      - name: 'Gradle Version'
        run: |
            ./gradlew --version
      - name: 'Build Polyfill'
        run: |
          ./gradlew "testOn${{ matrix.variant }}"
      - name: 'Stop Daemon'
        run: |
          ./gradlew --stop
